
[sign]
enabled = true
headers = From, Sender, Reply-To, Subject, Date, Message-ID, In-Reply-To, References, To, Cc, MIME-Version, Content-Type, Content-Language

[canon]
; body = relaxed

[verify]
enabled = false
